/* Generated by scripts/sync-typescript-api-models.ts. Do not edit. */

export type ZdpIsoDateTimeString = string;
export type ZdpLocaleString = string;
export type ZdpUriString = string;
export type ZdpCurrencyString = string;
export type ZdpDecimalString = string;

export type ZdpJsonPrimitive = string | number | boolean | null;
export type ZdpJsonValue = ZdpJsonPrimitive | readonly ZdpJsonValue[] | { readonly [key: string]: ZdpJsonValue };
export type ZdpJsonObject = Readonly<Record<string, ZdpJsonValue>>;

export type ZdpApiRuntimeFieldType = "string" | "boolean" | "integer" | "datetime" | "locale" | "uri" | "currency" | "decimal" | "json" | "json_object" | "string[]" | "json_object[]";
export interface ZdpApiRuntimeEnumFieldType { readonly enum: readonly string[]; }
export type ZdpApiRuntimeFieldDescriptor = ZdpApiRuntimeFieldType | ZdpApiRuntimeEnumFieldType;
export interface ZdpApiRuntimeSchemaDescriptor { readonly requiredFields: readonly string[]; readonly fieldTypes: Readonly<Record<string, ZdpApiRuntimeFieldDescriptor>>; }

export interface AbuseChallengeIssueRequest { readonly product_ref: string; readonly environment: string; readonly action: string; }
export interface AbuseChallengeIssueResponse { readonly challenge_ref: string; readonly challenge_kind: string; readonly widget_bootstrap: ZdpJsonObject; readonly expires_at: ZdpIsoDateTimeString; }
export interface AbuseChallengeRedeemRequest { readonly product_ref: string; readonly environment: string; readonly action: string; readonly challenge_response: ZdpJsonValue; }
export interface AbuseChallengeRedeemResponse { readonly verification_ref: string; readonly product_ref: string; readonly environment: string; readonly action: string; readonly verified_at: ZdpIsoDateTimeString; readonly expires_at: ZdpIsoDateTimeString; }
export interface AbuseVerificationVerifyRequest { readonly verification_ref: string; readonly consumer_operation_ref: string; readonly product_ref: string; readonly environment: string; readonly action: string; }
export interface AbuseVerificationVerifyResponse { readonly verification_state: string; readonly product_ref: string; readonly environment: string; readonly action: string; readonly verified_at: ZdpIsoDateTimeString; readonly consumed_at?: ZdpIsoDateTimeString; readonly safe_reason_code?: string; }
export interface AbuseHealthGetRequest {  }
export interface AbuseHealthGetResponse { readonly status: string; readonly checked_at: ZdpIsoDateTimeString; readonly adapter_status: string; readonly state_store_status: string; }
export interface AccessAuthorizationDecisionCreateRequest { readonly product_ref: string; readonly action: string; readonly resource_type: string; readonly resource_ref: string; readonly requested_scope_type: string; readonly requested_scope_ref: string; }
export interface AccessAuthorizationDecisionCreateResponse { readonly decision_ref: string; readonly decision: "allow" | "deny"; readonly reason_code: string; readonly policy_version: string; readonly data_revision: string; readonly subject_ref: string; readonly session_ref: string; readonly product_ref: string; readonly action: string; readonly resource_type: string; readonly resource_ref: string; readonly scope_type: string; readonly scope_ref: string; readonly decided_at: ZdpIsoDateTimeString; readonly decision_expires_at: ZdpIsoDateTimeString; readonly session_expires_at: ZdpIsoDateTimeString; readonly obligations: readonly string[]; }
export interface AuthSessionCurrentGetRequest {  }
export interface AuthSessionCurrentGetResponse { readonly session_ref: string; readonly actor_ref: string; readonly tenant_ref: string; readonly expires_at: ZdpIsoDateTimeString; }
export interface AuthRecoveryRequestCreateRequest { readonly login_identifier: string; readonly locale: ZdpLocaleString; }
export interface AuthRecoveryRequestCreateResponse { readonly recovery_request_id: string; readonly next_step: string; }
export interface AuthRegistrationCreateRequest { readonly login_id: string; readonly password: string; readonly policy_set_resolution_ref: string; readonly locale?: ZdpLocaleString; }
export interface AuthRegistrationCreateResponse { readonly registration_request_id: string; readonly next_step: string; }
export interface AuthSessionCreateRequest { readonly login_identifier: string; readonly verifier: string; }
export interface AuthSessionCreateResponse { readonly session_ref: string; readonly actor_ref: string; readonly tenant_ref: string; readonly expires_at: ZdpIsoDateTimeString; }
export interface AuthSessionRefreshRequest { readonly session_ref: string; readonly rotation_proof: string; }
export interface AuthSessionRefreshResponse { readonly session_ref: string; readonly expires_at: ZdpIsoDateTimeString; }
export interface AuthSessionRevokeCurrentRequest { readonly session_ref: string; }
export interface OAuthCallbackAcceptRequest { readonly provider: string; readonly state_ref: string; readonly callback_code: string; }
export interface OAuthCallbackAcceptResponse { readonly session_ref: string; readonly actor_ref: string; readonly tenant_ref: string; readonly expires_at: ZdpIsoDateTimeString; }
export interface PasskeyAssertionVerifyRequest { readonly challenge_ref: string; readonly assertion: ZdpJsonObject; }
export interface PasskeyAssertionVerifyResponse { readonly session_ref: string; readonly actor_ref: string; readonly tenant_ref: string; readonly expires_at: ZdpIsoDateTimeString; }
export interface PasskeyChallengeCreateRequest { readonly ceremony: string; readonly login_identifier: string; }
export interface PasskeyChallengeCreateResponse { readonly challenge_ref: string; readonly public_key_options_ref: string; readonly expires_at: ZdpIsoDateTimeString; }
export interface CustomerPolicySetResolveRequest { readonly product_ref: string; readonly environment: string; readonly capability: string; readonly locale: ZdpLocaleString; readonly jurisdiction_profile_ref?: string; readonly channel_ref?: string; readonly seller_role_ref?: string; }
export interface CustomerPolicySetResolveResponse { readonly policy_set_resolution_ref: string; readonly resolution_status: "resolved" | "unavailable" | "review_required"; readonly required_user_action: "no_user_action" | "notice" | "acknowledgement" | "explicit_consent" | "feature_restriction"; readonly policy_set_id: string; readonly policy_set_revision: string; readonly ordered_document_revision_ids: readonly string[]; readonly ordered_content_digests: readonly string[]; readonly presentation_rule_version: string; readonly document_projections: readonly ZdpJsonObject[]; readonly resolved_at: ZdpIsoDateTimeString; readonly expires_at: ZdpIsoDateTimeString; }
export interface OperatorSessionContextGetRequest {  }
export interface OperatorSessionContextGetResponse { readonly operator_ref: string; readonly organization_ref: string; readonly role: string; readonly capabilities: readonly string[]; readonly expires_at: ZdpIsoDateTimeString; readonly policy_version: string; }
export interface ProductLinkChallengeCompleteRequest { readonly challenge_ref: string; readonly approval_decision: string; }
export interface ProductLinkChallengeCompleteResponse { readonly challenge_ref: string; readonly state: "pending" | "approved" | "denied" | "expired" | "consumed"; readonly expires_at: ZdpIsoDateTimeString; }
export interface ProductLinkChallengeCreateRequest { readonly product_ref: string; readonly client_instance_ref: string; readonly client_correlation_ref: string; readonly proof_challenge: string; readonly requested_scope_refs: readonly string[]; }
export interface ProductLinkChallengeCreateResponse { readonly challenge_ref: string; readonly verification_uri: ZdpUriString; readonly expires_at: ZdpIsoDateTimeString; readonly poll_interval_seconds: number; }
export interface ProductLinkChallengeExchangeRequest { readonly challenge_ref: string; readonly client_correlation_ref: string; readonly proof_verifier: string; }
export interface ProductLinkChallengeExchangeResponse { readonly link_receipt_ref: string; readonly subject_ref: string; readonly consent_receipt_ref: string; readonly verified_at: ZdpIsoDateTimeString; readonly workspace_ref?: string; }
export interface ReferralUseCreateRequest { readonly referral_code: string; }
export interface ReferralUseCreateResponse { readonly referral_use_ref: string; readonly referral_status: string; readonly reward_status: string; readonly money_reward_status_ref: string; }
export interface CreditCheckoutIntentStatusGetRequest { readonly checkout_intent_ref: string; }
export interface CreditCheckoutIntentStatusGetResponse { readonly checkout_intent_ref: string; readonly operation_ref: string; readonly checkout_status: "created" | "payment_pending" | "credit_issuance_pending" | "completed" | "review_required" | "failed" | "cancelled" | "expired"; readonly payment_status: "not_started" | "pending" | "succeeded" | "review_required" | "failed" | "cancelled" | "expired"; readonly credit_issuance_status: "not_started" | "pending" | "succeeded" | "review_required" | "failed"; readonly return_receipt_status: "not_issued" | "available" | "consumed" | "expired"; readonly balance_refresh_required: boolean; readonly updated_at: ZdpIsoDateTimeString; readonly expires_at: ZdpIsoDateTimeString; readonly payment_attempt_ref?: string; readonly ledger_issuance_ref?: string; }
export interface CreditPackCatalogProjectionGetRequest { readonly product_ref: string; readonly scope_type: string; readonly scope_ref: string; readonly environment: string; readonly locale: ZdpLocaleString; }
export interface CreditPackCatalogProjectionGetResponse { readonly projection_ref: string; readonly product_ref: string; readonly scope_type: string; readonly scope_ref: string; readonly environment: string; readonly locale: ZdpLocaleString; readonly catalog_version: string; readonly currency: ZdpCurrencyString; readonly ship_tiers: readonly ZdpJsonObject[]; readonly sales_status: string; readonly projected_at: ZdpIsoDateTimeString; readonly expires_at: ZdpIsoDateTimeString; }
export interface CreditCheckoutIntentCreateRequest { readonly product_ref: string; readonly ship_tier_id: string; readonly scope_type: string; readonly scope_ref: string; readonly environment: string; readonly locale: ZdpLocaleString; readonly return_target_id: string; }
export interface CreditCheckoutIntentCreateResponse { readonly checkout_intent_ref: string; readonly operation_ref: string; readonly checkout_status: "created" | "payment_pending" | "credit_issuance_pending" | "completed" | "review_required" | "failed" | "cancelled" | "expired"; readonly payment_status: "not_started" | "pending" | "succeeded" | "review_required" | "failed" | "cancelled" | "expired"; readonly credit_issuance_status: "not_started" | "pending" | "succeeded" | "review_required" | "failed"; readonly return_receipt_status: "not_issued" | "available" | "consumed" | "expired"; readonly catalog_version: string; readonly price_snapshot_ref: string; readonly tax_snapshot_ref: string; readonly benefit_snapshot_ref: string; readonly return_target_id: string; readonly wallet_handoff_ref: string; readonly created_at: ZdpIsoDateTimeString; readonly expires_at: ZdpIsoDateTimeString; }
export interface CreditCheckoutReturnReceiptExchangeRequest { readonly return_receipt: string; readonly product_ref: string; readonly return_target_id: string; }
export interface CreditCheckoutReturnReceiptExchangeResponse { readonly checkout_intent_ref: string; readonly operation_ref: string; readonly checkout_status: "created" | "payment_pending" | "credit_issuance_pending" | "completed" | "review_required" | "failed" | "cancelled" | "expired"; readonly payment_status: "not_started" | "pending" | "succeeded" | "review_required" | "failed" | "cancelled" | "expired"; readonly credit_issuance_status: "not_started" | "pending" | "succeeded" | "review_required" | "failed"; readonly return_receipt_status: "not_issued" | "available" | "consumed" | "expired"; readonly balance_refresh_required: boolean; readonly consumed_at: ZdpIsoDateTimeString; }
export interface ReferralRewardStatusGetRequest { readonly referral_use_ref: string; }
export interface ReferralRewardStatusGetResponse { readonly referral_use_ref: string; readonly reward_status: string; readonly reward_recipient: string; readonly eligible_settled_paid_amount_credit_unit: ZdpDecimalString; readonly excluded_refund_amount_credit_unit: ZdpDecimalString; readonly excluded_chargeback_amount_credit_unit: ZdpDecimalString; readonly abuse_review_status: string; readonly campaign_policy_version: string; readonly referral_reward_confirmation_ref: string; }
export interface SupportCaseCreateRequest { readonly request_kind: string; readonly reply_address: string; readonly message: string; readonly locale: ZdpLocaleString; readonly abuse_verification_ref: string; readonly product_id?: string; readonly privacy_action?: string; readonly account_ref?: string; }
export interface SupportCaseCreateResponse { readonly case_id: string; readonly received_at: ZdpIsoDateTimeString; readonly verification_state: string; readonly next_step: string; }
export interface SupportCaseDetailReadRequest { readonly expected_source_version: number; readonly purpose: string; readonly reason: string; readonly audit_request_id: string; readonly audit_policy_version: string; }
export interface SupportCaseDetailReadResponse { readonly case_id: string; readonly source_version: number; readonly request_kind: string; readonly source_state: string; readonly sanitized_message: string; readonly masked_reply_address: string; readonly locale: ZdpLocaleString; readonly opened_at: ZdpIsoDateTimeString; readonly last_activity_at: ZdpIsoDateTimeString; readonly content_access: string; readonly product_id?: string; readonly privacy_action?: string; }
export interface SupportCaseReplyAddressVerifyRequest { readonly verification_ref: string; }
export interface SupportCaseReplyAddressVerifyResponse { readonly case_id: string; readonly source_version: number; readonly source_state: string; readonly changed_at: ZdpIsoDateTimeString; readonly replayed: boolean; }
export interface SupportCaseReplyCreateRequest { readonly expected_source_version: number; readonly message: string; readonly reason: string; readonly audit_request_id: string; readonly audit_policy_version: string; }
export interface SupportCaseReplyCreateResponse { readonly case_id: string; readonly reply_id: string; readonly source_version: number; readonly source_state: string; readonly delivery_state: string; readonly created_at: ZdpIsoDateTimeString; readonly replayed: boolean; }
export interface SupportCaseStatusChangeRequest { readonly expected_source_version: number; readonly target_state: string; readonly reason: string; readonly audit_request_id: string; readonly audit_policy_version: string; }
export interface SupportCaseStatusChangeResponse { readonly case_id: string; readonly source_version: number; readonly source_state: string; readonly changed_at: ZdpIsoDateTimeString; readonly replayed: boolean; }

export interface ZdpApiSchemaTypeMap {
  readonly "contracts/apis/abuse-api/challenge.yaml#AbuseChallengeIssueRequest": AbuseChallengeIssueRequest;
  readonly "contracts/apis/abuse-api/challenge.yaml#AbuseChallengeIssueResponse": AbuseChallengeIssueResponse;
  readonly "contracts/apis/abuse-api/challenge.yaml#AbuseChallengeRedeemRequest": AbuseChallengeRedeemRequest;
  readonly "contracts/apis/abuse-api/challenge.yaml#AbuseChallengeRedeemResponse": AbuseChallengeRedeemResponse;
  readonly "contracts/apis/abuse-api/challenge.yaml#AbuseVerificationVerifyRequest": AbuseVerificationVerifyRequest;
  readonly "contracts/apis/abuse-api/challenge.yaml#AbuseVerificationVerifyResponse": AbuseVerificationVerifyResponse;
  readonly "contracts/apis/abuse-api/health.yaml#AbuseHealthGetRequest": AbuseHealthGetRequest;
  readonly "contracts/apis/abuse-api/health.yaml#AbuseHealthGetResponse": AbuseHealthGetResponse;
  readonly "contracts/apis/core-api/access-decision.yaml#AccessAuthorizationDecisionCreateRequest": AccessAuthorizationDecisionCreateRequest;
  readonly "contracts/apis/core-api/access-decision.yaml#AccessAuthorizationDecisionCreateResponse": AccessAuthorizationDecisionCreateResponse;
  readonly "contracts/apis/core-api/auth-session-consumer.yaml#AuthSessionCurrentGetRequest": AuthSessionCurrentGetRequest;
  readonly "contracts/apis/core-api/auth-session-consumer.yaml#AuthSessionCurrentGetResponse": AuthSessionCurrentGetResponse;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthRecoveryRequestCreateRequest": AuthRecoveryRequestCreateRequest;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthRecoveryRequestCreateResponse": AuthRecoveryRequestCreateResponse;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthRegistrationCreateRequest": AuthRegistrationCreateRequest;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthRegistrationCreateResponse": AuthRegistrationCreateResponse;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthSessionCreateRequest": AuthSessionCreateRequest;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthSessionCreateResponse": AuthSessionCreateResponse;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthSessionRefreshRequest": AuthSessionRefreshRequest;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthSessionRefreshResponse": AuthSessionRefreshResponse;
  readonly "contracts/apis/core-api/auth-session.yaml#AuthSessionRevokeCurrentRequest": AuthSessionRevokeCurrentRequest;
  readonly "contracts/apis/core-api/auth-session.yaml#OAuthCallbackAcceptRequest": OAuthCallbackAcceptRequest;
  readonly "contracts/apis/core-api/auth-session.yaml#OAuthCallbackAcceptResponse": OAuthCallbackAcceptResponse;
  readonly "contracts/apis/core-api/auth-session.yaml#PasskeyAssertionVerifyRequest": PasskeyAssertionVerifyRequest;
  readonly "contracts/apis/core-api/auth-session.yaml#PasskeyAssertionVerifyResponse": PasskeyAssertionVerifyResponse;
  readonly "contracts/apis/core-api/auth-session.yaml#PasskeyChallengeCreateRequest": PasskeyChallengeCreateRequest;
  readonly "contracts/apis/core-api/auth-session.yaml#PasskeyChallengeCreateResponse": PasskeyChallengeCreateResponse;
  readonly "contracts/apis/core-api/customer-policy-registry.yaml#CustomerPolicySetResolveRequest": CustomerPolicySetResolveRequest;
  readonly "contracts/apis/core-api/customer-policy-registry.yaml#CustomerPolicySetResolveResponse": CustomerPolicySetResolveResponse;
  readonly "contracts/apis/core-api/operator-session-context.yaml#OperatorSessionContextGetRequest": OperatorSessionContextGetRequest;
  readonly "contracts/apis/core-api/operator-session-context.yaml#OperatorSessionContextGetResponse": OperatorSessionContextGetResponse;
  readonly "contracts/apis/core-api/product-link.yaml#ProductLinkChallengeCompleteRequest": ProductLinkChallengeCompleteRequest;
  readonly "contracts/apis/core-api/product-link.yaml#ProductLinkChallengeCompleteResponse": ProductLinkChallengeCompleteResponse;
  readonly "contracts/apis/core-api/product-link.yaml#ProductLinkChallengeCreateRequest": ProductLinkChallengeCreateRequest;
  readonly "contracts/apis/core-api/product-link.yaml#ProductLinkChallengeCreateResponse": ProductLinkChallengeCreateResponse;
  readonly "contracts/apis/core-api/product-link.yaml#ProductLinkChallengeExchangeRequest": ProductLinkChallengeExchangeRequest;
  readonly "contracts/apis/core-api/product-link.yaml#ProductLinkChallengeExchangeResponse": ProductLinkChallengeExchangeResponse;
  readonly "contracts/apis/core-api/referral.yaml#ReferralUseCreateRequest": ReferralUseCreateRequest;
  readonly "contracts/apis/core-api/referral.yaml#ReferralUseCreateResponse": ReferralUseCreateResponse;
  readonly "contracts/apis/money-api/credit-purchase-read.yaml#CreditCheckoutIntentStatusGetRequest": CreditCheckoutIntentStatusGetRequest;
  readonly "contracts/apis/money-api/credit-purchase-read.yaml#CreditCheckoutIntentStatusGetResponse": CreditCheckoutIntentStatusGetResponse;
  readonly "contracts/apis/money-api/credit-purchase-read.yaml#CreditPackCatalogProjectionGetRequest": CreditPackCatalogProjectionGetRequest;
  readonly "contracts/apis/money-api/credit-purchase-read.yaml#CreditPackCatalogProjectionGetResponse": CreditPackCatalogProjectionGetResponse;
  readonly "contracts/apis/money-api/credit-purchase.yaml#CreditCheckoutIntentCreateRequest": CreditCheckoutIntentCreateRequest;
  readonly "contracts/apis/money-api/credit-purchase.yaml#CreditCheckoutIntentCreateResponse": CreditCheckoutIntentCreateResponse;
  readonly "contracts/apis/money-api/credit-purchase.yaml#CreditCheckoutReturnReceiptExchangeRequest": CreditCheckoutReturnReceiptExchangeRequest;
  readonly "contracts/apis/money-api/credit-purchase.yaml#CreditCheckoutReturnReceiptExchangeResponse": CreditCheckoutReturnReceiptExchangeResponse;
  readonly "contracts/apis/money-api/referral-reward.yaml#ReferralRewardStatusGetRequest": ReferralRewardStatusGetRequest;
  readonly "contracts/apis/money-api/referral-reward.yaml#ReferralRewardStatusGetResponse": ReferralRewardStatusGetResponse;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseCreateRequest": SupportCaseCreateRequest;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseCreateResponse": SupportCaseCreateResponse;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseDetailReadRequest": SupportCaseDetailReadRequest;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseDetailReadResponse": SupportCaseDetailReadResponse;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseReplyAddressVerifyRequest": SupportCaseReplyAddressVerifyRequest;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseReplyAddressVerifyResponse": SupportCaseReplyAddressVerifyResponse;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseReplyCreateRequest": SupportCaseReplyCreateRequest;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseReplyCreateResponse": SupportCaseReplyCreateResponse;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseStatusChangeRequest": SupportCaseStatusChangeRequest;
  readonly "contracts/apis/support-api/intake.yaml#SupportCaseStatusChangeResponse": SupportCaseStatusChangeResponse;
}
